title: Stack Problems
description: My Personal Stack Problems
author: Agung Setiaji
github: https://github.com/mragungsetiaji
about: Data Science and Analytics 
disqus_shortname: mragungsetiaji
google_analytics: UA-115104999-1
avatar_url: /static/img/avatar.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "https://facebook.com/mragungsetiaji"
    - icon: fa-twitter
      link: "https://twitter.com/mragungsetiaji"
    - icon: fa-linkedin
      link: "https://linkedin.com/in/mragungsetiaji"
    - icon: fa-stack-exchange
      link: "#"
    - icon: fa-github
      link: "https://github.com/mragungsetiaji"

share:
  twitter_username: github.io
  fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "https://mragungsetiaji.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
